Agenda.UI.SITE/Controllers/ContatoController.cs
using Agenda.Aplicacao.Interfaces;
using Agenda.Aplicacao.ViewModel;
using Agenda.Dominio.Core.Notificacoes;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Agenda.UI.SITE.Controllers
{
    public class ContatoController : BaseController
    {
        private readonly IContatoAppService _contatoAppService;
        private static List<ContatoTelefoneViewModel> _contatoTelefoneViewModels;
        private static List<ContatoEmailViewModel> _contatoEmailViewModels;
        private static ContatoViewModel _contatoViewModel;
        private readonly IContatoTelefoneAppService _contatoTelefoneAppService;
        private readonly IContatoEmailAppService _contatoEmailAppService;
        public ContatoController(IContatoEmailAppService contatoEmailAppService, IContatoTelefoneAppService contatoTelefoneAppService, IContatoAppService contatoAppService, INotificationHandler<DomainNotification> notifications) : base(notifications)
        {
            _contatoEmailAppService = contatoEmailAppService;
            _contatoAppService = contatoAppService;
            _contatoTelefoneAppService = contatoTelefoneAppService;
            ViewBag.Detalhe = "";
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_contatoAppService.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            if (_contatoViewModel == null)
                _contatoViewModel = new ContatoViewModel();

            _contatoViewModel.ContatoTelefones = _contatoTelefoneViewModels;
            _contatoViewModel.ContatoEmails = _contatoEmailViewModels;

            ViewBag.Status = "NovoContato";

            return View(_contatoViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ContatoViewModel contatoViewModel)
        {
            contatoViewModel = _contatoViewModel;
            _contatoAppService.Registrar(contatoViewModel);

            if (IsValidOperation())
            {
                ViewBag.Sucesso = "Contato Cadastrado!";
                contatoViewModel = new ContatoViewModel();
                _contatoTelefoneViewModels = new List<ContatoTelefoneViewModel>();
                _contatoEmailViewModels = new List<ContatoEmailViewModel>();
                _contatoViewModel = null;
            }

            return View(contatoViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddContatoEmail(ContatoViewModel contatoViewModel)
        {
            if (TryValidateModel(contatoViewModel.ContatoEmail))
            {
                if (_contatoEmailViewModels == null)
                    _contatoEmailViewModels = new List<ContatoEmailViewModel>();

                if (!string.IsNullOrEmpty(contatoViewModel.ContatoEmail.Email?.Trim() ?? "") && !_contatoEmailViewModels.Exists(x => x.Email == contatoViewModel.ContatoEmail.Email))
                {
                    _contatoEmailViewModels.Add(new ContatoEmailViewModel() { Email = contatoViewModel.ContatoEmail.Email });
                    contatoViewModel.ContatoEmail = new ContatoEmailViewModel();
                }
                else { ViewBag.Error = "Ja existe este Email."; }

                if (IsValidOperation())
                    ViewBag.Sucesso = "Email Cadastrado!";

                _contatoViewModel = contatoViewModel;
            }


            return RedirectToAction("Create");
        }
        [HttpGet]
        public IActionResult DeletarEmailLst(string email)
        {
            if (!string.IsNullOrEmpty(email?.Trim() ?? "") && _contatoEmailViewModels.Exists(x => x.Email == email))
            {
                _contatoEmailViewModels.RemoveAll(x => x.Email == email);
            }
            else { ViewBag.Error = "Email não encontrado."; }

            if (IsValidOperation())
                ViewBag.Sucesso = "Email Deletado!";

            return RedirectToAction("Create");
        }
        [HttpGet]
        public IActionResult DeletarEmail(long idContatoEmail, long idContato)
        {
            _contatoEmailAppService.Remover(new ContatoEmailViewModel { IdContatoEmail = idContatoEmail });

            if (IsValidOperation())
                ViewBag.Sucesso = "Email Deletado!";

            return RedirectToAction("EditarContato", new { idContato = idContato });
        }
        [HttpGet]
        public IActionResult DeletarTelefone(long idContatoTelefone, long idContato)
        {
            _contatoTelefoneAppService.Remover(new ContatoTelefoneViewModel { IdContatoTelefone = idContatoTelefone });

            if (IsValidOperation())
                ViewBag.Sucesso = "Telefone Deletado!";

            return RedirectToAction("EditarContato", new { idContato });
        }
        [HttpGet]
        public IActionResult DeletarTelefoneLista(string telefone)
        {
            if (!string.IsNullOrEmpty(telefone?.Trim() ?? "") && _contatoTelefoneViewModels.Exists(x => x.Telefone == telefone))
            {
                _contatoTelefoneViewModels.RemoveAll(x => x.Telefone == telefone);
            }
            else { ViewBag.Error = "Telefone não encontrado."; }

            if (IsValidOperation())
                ViewBag.Sucesso = "Telefone Deletado!";

            return RedirectToAction("Create");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddContatoTelefone(ContatoViewModel contatoViewModel)
        {
            if (TryValidateModel(contatoViewModel.ContatoTelefone))
            {
                if (_contatoTelefoneViewModels == null)
                    _contatoTelefoneViewModels = new List<ContatoTelefoneViewModel>();

                if (!string.IsNullOrEmpty(contatoViewModel.ContatoTelefone.Telefone?.Trim() ?? "") && !_contatoTelefoneViewModels.Exists(x => x.Telefone == contatoViewModel.ContatoTelefone.Telefone))
                {
                    _contatoTelefoneViewModels.Add(new ContatoTelefoneViewModel() { Telefone = contatoViewModel.ContatoTelefone.Telefone });
                    contatoViewModel.ContatoTelefone = new ContatoTelefoneViewModel();
                }
                else { ViewBag.Error = "Ja existe este telefone."; }

                if (IsValidOperation())
                    ViewBag.Sucesso = "Telefone Cadastrado!";

                _contatoViewModel = contatoViewModel;
            }

            return RedirectToAction("Create");
        }
        [HttpGet]
        public IActionResult Detalhe()
        {
            ViewBag.Detalhe = "Detalhe";
            return View(_contatoViewModel);
        }
        [HttpPost]
        public IActionResult DetalheContato(long idContato)
        {
            _contatoViewModel = _contatoAppService.GetById(idContato);

            return RedirectToAction("Detalhe");
        }

        [HttpPost]
        public IActionResult DeletarContato(long idContato)
        {
            _contatoViewModel = _contatoAppService.GetById(idContato);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditarContato(long idContato)
        {
            _contatoViewModel = _contatoAppService.GetById(idContato);

            ViewBag.Status = "EditarContato";

            return View(_contatoViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletarContatoEmail(long idContato)
        {
            _contatoViewModel = _contatoAppService.GetById(idContato);

            return View(_contatoViewModel);
        }

    }
}

Agenda.UI.SITE/ViewComponents/SummaryViewComponent.cs
using Agenda.Dominio.Core.Notificacoes;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Agenda.UI.SITE.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationsHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationsHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult((_notifications.GetNotificacoes()));
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Valor));

            return View();
        }
    }
}

Agenda.UI.SITE/Views/Contato/Create.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Novo Contato</h2>
<br />

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <vc:summary />

            <partial name="_Contato" model="Model" />

            <partial name="_ContatoTelefone" model="Model"  />

            <partial name="_ContatoEmail" model="Model" />


            @*<div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>*@

            @*<div class="form-group">
                    <label asp-for="ContatoTelefone.Telefone" class="control-label"></label>
                    <input asp-for="ContatoTelefone.Telefone" class="form-control" />
                    <span asp-validation-for="ContatoTelefone.Telefone" class="text-danger"></span>
                    <button id="btnNovoTel" type="submit" class="btn btn-default" name="provider" value="@Model" title="Adicionar um novo Telefone" asp-action="AddContatoTelefone">Adicionar</button>
                </div>*@

            @*<div class="form-group">
                    <label asp-for="ContatoEmail.Email" class="control-label"></label>
                    <input asp-for="ContatoEmail.Email" class="form-control" />
                    <span asp-validation-for="ContatoEmail.Email" class="text-danger"></span>
                    <button id="btnNovoEmail" type="submit" class="btn btn-default" name="provider" value="@Model" title="Adicionar um novo Telefone" asp-action="AddContatoEmail">Adicionar</button>
                </div>*@

            <div class="form-group">
                <input type="submit" value="Create" asp-route-contatoViewModel="@Model" class="btn btn-default" />
            </div>
        </form>

    </div>
    <div class="col-md-3 col-md-offset-1">
        <section>
            <h4>Telefones Cadastrados.</h4>
            <hr />
            <partial name="_ListaTelefone" model="Model?.ContatoTelefones" />
        </section>
    </div>
    <div class="col-md-3 col-md-offset-0">
        <section>
            <h4>Emails Cadastrados.</h4>
            <hr />
            <partial name="_ListaEmail" model="Model?.ContatoEmails" />
        </section>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

Agenda.UI.SITE/Views/Contato/Detalhe.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel

<div>
    <h4>Detalhe do Contato</h4>
    <hr />
    <dl class="dl-horizontal">
        <vc:summary />

        <partial name="_Contato" model="Model" />

        <partial name="_ContatoTelefone" model="Model" />

        <partial name="_ContatoEmail" model="Model" />
    </dl>
</div>
<div>
    <a asp-action="Index">Voltar</a>
</div>

Agenda.UI.SITE/Views/Contato/EditarContato.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel

<h4>Editar Contato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarContato">
            <vc:summary />

            <partial name="_Contato" model="Model" />

            <partial name="_ContatoTelefone" model="Model" />

            <partial name="_ContatoEmail" model="Model" />
        </form>
    </div>

    <div class="col-md-3 col-md-offset-1">
        <section>
            <h4>Telefones Cadastrados.</h4>
            <hr />
            <partial name="_ListaTelefone" model="Model?.ContatoTelefones" />
        </section>
    </div>
    <div class="col-md-3 col-md-offset-0">
        <section>
            <h4>Emails Cadastrados.</h4>
            <hr />
            <partial name="_ListaEmail" model="Model?.ContatoEmails" />
        </section>
    </div>
</div>



<div>
    <a asp-action="Index">Voltar</a>
</div>

Agenda.UI.SITE/Views/Contato/Index.cshtml
@model IEnumerable<Agenda.Aplicacao.ViewModel.ContatoViewModel>

@{
    ViewData["Title"] = "Contatos";
}

<h2>Lista de Contatos</h2>
<br/>


<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Cadastrar Novo" class="glyphicon glyphicon-plus-sign"></span> Cadastrar Novo
                </a>
            </div>
        </div>
    </div>
</div>
<br />

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdContato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtCadastro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdContato)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DtCadastro)
                </td>
                <td>
                    <a asp-action="EditarContato" asp-controller="Contato" asp-route-idContato="@item.IdContato" title="Edit" class="btn btn-warning">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>

                    <a asp-action="DetalheContato" asp-controller="Contato" asp-route-idContato="@item.IdContato" title="Details" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </a>

                    <a asp-action="DeletarContato" asp-controller="Contato" asp-route-idContato="@item.IdContato" title="Delete" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Agenda.UI.SITE/Views/Contato/_Contato.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel


<div class="form-group">
    <label asp-for="Nome" class="control-label"></label>
    <input asp-for="Nome" class="form-control" />
    <span asp-validation-for="Nome" class="text-danger"></span>
</div>

Agenda.UI.SITE/Views/Contato/_ContatoEmail.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel

<div class="form-group">
    <label asp-for="ContatoEmail.Email" class="control-label"></label>
    <input asp-for="ContatoEmail.Email" class="form-control" />
    <span asp-validation-for="ContatoEmail.Email" class="text-danger"></span>
    @if (ViewBag.Detalhe != "Detalhe")
    {
        <button id="btnNovoEmail" type="submit" class="btn btn-default" name="provider" value="@Model" title="Adicionar um novo Telefone" asp-action="AddContatoEmail">Adicionar</button>
    }
</div>

Agenda.UI.SITE/Views/Contato/_ContatoTelefone.cshtml
@model Agenda.Aplicacao.ViewModel.ContatoViewModel

<div class="form-group">
    <label asp-for="ContatoTelefone.Telefone" class="control-label"></label>
    <input asp-for="ContatoTelefone.Telefone" class="form-control" />
    <span asp-validation-for="ContatoTelefone.Telefone" class="text-danger"></span>
    @if (ViewBag.Detalhe != "Detalhe")
    {
        <button id="btnNovoTel" type="submit" class="btn btn-default" name="provider" value="@Model" title="Adicionar um novo Telefone" asp-action="AddContatoTelefone">Adicionar</button>
    }
  
</div>

Agenda.UI.SITE/Views/Contato/_ListaEmail.cshtml
@model IEnumerable<Agenda.Aplicacao.ViewModel.ContatoEmailViewModel>

<section>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @if (ViewBag.Status == "NovoContato")
                            {
                            <a asp-action="DeletarEmailLst" asp-route-email="@item.Email" title="Delete" class="btn btn-danger">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                            }
                            else if (ViewBag.Status == "EditarContato")
                            {
                                <a asp-action="DeletarEmail" asp-route-idContatoEmail="@item.IdContatoEmail" asp-route-idContato="@item.IdContato" title="Delete" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            }
                            
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</section>
@*<script>
    $.ajax({
        url: "DeletarEmail",
        type: 'Post',
        success: function (response) {
            $('').html(reponse);
        }
    })
</script>*@

Agenda.UI.SITE/Views/Contato/_ListaTelefone.cshtml
@model IEnumerable<Agenda.Aplicacao.ViewModel.ContatoTelefoneViewModel>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefone)
                    </td>
                    <td>
                        @if (ViewBag.Status == "NovoContato")
                        {
                            <a asp-action="DeletarTelefoneLista" asp-route-telefone="@item.Telefone" title="Delete" class="btn btn-danger">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        }
                        else if (ViewBag.Status == "EditarContato")
                        {
                            <a asp-action="DeletarTelefone" asp-route-idContatoTelefone="@item.IdContatoTelefone"  asp-route-idContato="@item.IdContato" title="Delete" class="btn btn-danger">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>